### PR TITLE
[php/nix] pull in sdl ext

### PR DESCRIPTION
**Pull request by jbboehr**
If you don't want to pin it, can change:

```nix
{
 src = builtins.fetchTarball "https://github.com/shish/php-sdl/archive/refs/heads/master.tar.gz";
}
```

Or jump on the flake train and let `nix flake update` handle it :P

### CODE REVIEW

**Comment by jbboehr** [comment]
Just an example if you want to do it that way, feel free to close or whatever.

**Comment by shish** [comment]
Now that you mention it, I should check if my custom fork is still necessary, or if the changes got merged into upstream and released -- if it's still needed, then this looks good to merge :)

I am also interested in moving to flakes, they look nice, but I don't know enough to migrate by myself ^^;

**Comment by jbboehr** [comment]
Not tagged yet: https://github.com/Ponup/php-sdl/commit/ee620e64e12265bc523784b2e278dc9e6bd2b30a

**Comment by jbboehr** [comment]
I went to test upstream sdl in docker and I guess `debian:unstable` has removed php8.1? If you want to upgrade to 8.2: https://github.com/shish/rosettaboy/commit/404073948843645abb97598a22dab6e61cd9c4f5

**Comment by shish** [comment]
I've added #111 for discussion of flakes - they seem great but I need to do a lot more reading of the manual before I understand them, pull requests would be welcome though ^^;;

**Pull request merged**
